services:

  nginx:
    image: nginx:alpine
    container_name: microcampo-nginx
    volumes:
      - ./src:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    environment:
      - PHP_FPM_HOST=php
    ports:
      - "8000:80"               # solo desarrollo (local)
    labels:
      - VIRTUAL_HOST=${DOMAIN}  # solo producci√≥n
      - LETSENCRYPT_HOST=${DOMAIN}
      - LETSENCRYPT_EMAIL=${EMAIL}
    networks:
      - default
      - proxy
    restart: unless-stopped

  php:
    build: .
    container_name: microcampo-php
    volumes:
      - ./src:/var/www/html
    networks:
      - default
    restart: unless-stopped


  mariadb:
    image: mariadb:latest
    container_name: microcampo-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: microcampo
      MYSQL_USER: pablo
      MYSQL_PASSWORD: 1234
      TZ: America/Argentina/Buenos_Aires
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - default
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - "8080:80"           # solo desarrollo
    depends_on:
      - mariadb
    networks:
      - default
    restart: unless-stopped

volumes:
  mariadb_data:

networks:
  proxy:
    external: true
  default:
    driver: bridge
